### ISSUE TITLE
problem with Nim 1.6.0

### ISSUE THREAD

**Issue by Martinix75** [beef331/picostdlib#15]
good morning,
i just found a problem with nim 1.6.0 that didn't exist with nim 1.4.8!

import random (just import it to generate the error !! )

now create an error:
/home/andrea/ProgPicoNim/test160/src/os.nim(63, 10) Error: OS module not ported to your operating system!
oserr.nim(94)            raiseOSError
Error: unhandled exception: No such file or directory
Additional info: "(\"csource/@mtest160.nim.c\", \"csource/test160.c\", \"No such file or directory\")" [OSError]

i know you probably can't do anything about it, but i tell you (maybe it's a bug of nim 1.6.0 ?????) 
bye!

**Comment by beef331** [comment]
Yea the pico doesnt have an OS unless using RTOS, so much of the Nim stdlib that depends on `os` will not work. Ideally we make more bindings for pico, but I've been quite distracted as of late. Might be worthwhile to just use `c2nim` or similar to make bindings even though they're not idiomatic.
