### ISSUE TITLE
Error: cannot open file: picostdlib

### ISSUE THREAD

**Issue by auxym** [beef331/picostdlib#30]
I followed the setup instructions, and when running `piconim build firmware.nim` (my project is called `firmware`) I get the following error:

```
pico-nim : create raspberry pi pico projects using Nim
Hint: used config file '/home/francis/.choosenim/toolchains/nim-1.6.2/config/nim.cfg' [Conf]
Hint: used config file '/home/francis/.choosenim/toolchains/nim-1.6.2/config/config.nims' [Conf]
....................................................
/home/francis/source/tmpcb-macropad/firmware/src/firmware.nim(2, 8) Error: cannot open file: picostdlib
oserr.nim(95)            raiseOSError
Error: unhandled exception: No such file or directory
Additional info: ("csource/@mfirmware.nim.c", "csource/firmware.c") [OSError]
```

Nim 1.6.2 on Linux (manjaro).

I can probably look into the issue myself in the next couple of days, just wanted to write it down somewhere.

**Comment by beef331** [comment]
We're undergoing some refactoring so `picostdlib` is no longer a module. Sorry for the inconvenience, all functionality that it exported is now in `picostdlib/stdio`.
