### ISSUE TITLE
Colourized terminal output

### ISSUE THREAD

**Issue by casey-SK** [beef331/picostdlib#4]
Similar to how nimble looks.

1. when the program is called with some arguments, print a `hint: ` message to read back the interpreted arguments/option/flag
2. tell the user whenever something is being pulled from the world wide web.
3. nice colourized error messages.

**Comment by beef331** [comment]
For reference did replace the exception handing with a error message as such https://github.com/beef331/picostdlib/blob/master/src/piconim.nim#L5
