### ISSUE TITLE
Move some hardcoded compiler flags to a nim.cfg file

### ISSUE THREAD

**Issue by auxym** [beef331/picostdlib#44]
See: https://github.com/beef331/picostdlib/blob/b1bae1b47f7f0057f3973f2a330fb90c9d116bd2/src/piconim.nim#L21

Library users might want to override some of these flags. Eg. running a debug or danger build instead of release, or ORC instead of ARC. I therefore propose to add a `nim.cfg` file to the template that specifies these flags, and remove the hardcoded values in piconim. The flags that are "absolutely necessary" for a working build should probably stay where they are (`--cpu`, `--nimcache`, `useMalloc`).

This once again breaks backwards compatibility with previously created projects (sorry). Users that want to upgrade would need to copy the new nim.cfg file in their project.

Thoughts?

**Comment by beef331** [comment]
`config.nims` is what I'd prefer `nim.cfg` is for local overrides in my view. I'm not too worried about previous projects given this is not an overly used library I would wager.
