### ISSUE TITLE
example usb

### ISSUE THREAD

**Issue by Martinix75** [beef331/picostdlib#6]
thanks Jeson for the very useful getCharWithTimeout () implementation !!
as a test I wrote a small test program, if you want to include it among the examples! 
[serialUsb.nim.zip](https://github.com/beef331/picostdlib/files/7083832/serialUsb.nim.zip)

**Comment by beef331** [comment]
I'd like a PR if you have the time.

**Comment by Martinix75** [comment]
PR? sorry but my English is not the best, what do you mean by PR?

**Comment by beef331** [comment]
A pull request, submiting the addition to the repo with git.

**Comment by Martinix75** [comment]
in fact it is one of the things that I have to learn well to do pull requests. I've never done them. but I promise that I study and at least I try (it's now past to learn)

**Comment by Martinix75** [comment]
andrea@tec-martin:~/Documenti/Git/picostdlib/examples> git push -u origin master 
remote: Invalid username or password.
